### ISSUE TITLE
Lightmap Importing if available

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xr3ngine#482]

**Comment by XiaNi** [comment]
In file you provided Lightmap properties stored like this:
```
Scene.userData:
  TLM_EngineProperties:
    tlm_bake_mode: 1
    tlm_dilation_margin: 8
    tlm_directional_mode: 0
    tlm_lightmap_savedir: "/home/beast/Downloads/LightmapsX/"
    tlm_mode: 1
    tlm_quality: 1
    tlm_resolution_scale: 0
  TLM_SceneProperties:
    tlm_alert_on_finish: 1
    tlm_apply_on_unwrap: 1
    tlm_denoise_use: 1
    tlm_encoding_mode: 0
    tlm_encoding_use: 1
    tlm_headless: 0
```
```
group.userData:
  Lightmap: "/home/beast/Downloads/LightmapsX/Racetrack_denoised_encoded.png"
  TLM_ObjectProperties:
    tlm_mesh_lightmap_resolution: 6
    tlm_mesh_lightmap_unwrap_mode: 1
    tlm_mesh_lightmap_use: 1
  name: "Racetrack"
```
but lightmap files provided in 'Lightmaps' folder does not match names like "Racetrack_denoised_encoded.png".
so for now i used just `group.userData.name` to load like 'Lightmaps/' + name + '.hdr'

the next problem is that hdr files not loading with `RGBELoader`, page hangs for some time (minute or so), and then crashes.
